name: Build
on:
    push:
        tags:
          - "^test$"
jobs:
    gobuild:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup Go
              uses: actions/setup-go@v3
              with:
                  go-version: '1.21.x'
            - name: Build day one
              run: go build -v ./day01/*.go
            - name: Build day two
              run: go build -v ./day02/*.go
            - name: Display Go version
              run: go version
            - name: List files in the repository
              run: |
                  ls ${{ github.workspace }}
            - run: echo "This job's status is ${{ job.status }}."
